### PR TITLE
Add audio plugin support

### PR DESCRIPTION
**Pull request by hfiguiere**
This add support for Audio Plugins: LADSPA and LV2.

### CODE REVIEW

**Comment by hfiguiere** [comment]
(I'm a still waiting on a few to be added to Flathub, PRs have been submitted)

**Comment by eszlari** [comment]
When trying `org.freedesktop.LinuxAudio.Lv2Plugins.Surge`, I get:
```
suil error: Failed to open module lib/audacitylibsuil_x11_in_gtk3.so (lib/audacitylibsuil_x11_in_gtk3.so: cannot open shared object file: No such file or directory)
```
The actual name of that file is `/app/lib/audacity/suil_x11_in_gtk3.so`. Maybe this related to the switch from autotools to cmake.

I also couldn't get any output from `org.freedesktop.LinuxAudio.Lv2Plugins.Helm`. Maybe it's related to the above problem.

The filter from `org.freedesktop.LinuxAudio.Lv2Plugins.swh` I tested worked.

**Comment by eszlari** [comment]
I'm also not sure, how the bundled lv2 libs fit into the picture:
```
-- ========== Configuring lv2 ==========
-- Checking for modules 'lilv-0 >= 0.24.6;lv2 >= 1.16.0;serd-0 >= 0.30.2;sord-0 >= 0.16.4;sratom-0 >= 0.6.4;suil-0 >= 0.10.6'
--   Package 'lilv-0', required by 'virtual:world', not found
--   Package 'lv2', required by 'virtual:world', not found
--   Package 'serd-0', required by 'virtual:world', not found
--   Package 'sord-0', required by 'virtual:world', not found
--   Package 'sratom-0', required by 'virtual:world', not found
--   Package 'suil-0', required by 'virtual:world', not found
-- Using 'lv2' local library
```

**Comment by hfiguiere** [comment]
Maybe we should try with the lilv.json shared-module. I'll see if I can fix that.

**Comment by hfiguiere** [comment]
Also I missed Audacity support VST as well....

**Comment by hfiguiere** [comment]
With lv2 as a dependency the path for the suil library seems to be better, albeit the error still happens

**Comment by hfiguiere** [comment]
About the suil error, using the app provided version:

It tries to load `lib/audacitylibsuil_x11_in_gtk3`. I have fixes to two of the three errors. 

Now I just get 
```
suil error: Failed to open module lib/audacity/suil_x11_in_gtk3.so (lib/audacity/suil_x11_in_gtk3.so: cannot open shared object file: No such file or directory)
```
Doing a strace really show that it is trying to stat `lib/audacity/suil_x11_in_gtk3.so` while `/app/ lib/audacity/suil_x11_in_gtk3.so` exists.

**Comment by hfiguiere** [comment]
@eszlari this last push fixes UI embedding. wayland has to be disabled for GtkPlug to work.

**Comment by hfiguiere** [comment]
As for the generators I am not sure why they are not working. I even tried with my MIDI controller. But this is not worse than before though.

**Comment by hfiguiere** [comment]
Anything else needs to be done? I don't think that one plugin not working completely is a good reason. I have tested other effects and they work.

**Comment by eszlari** [comment]
Have you upstreamed the patch?

**Comment by hfiguiere** [comment]
I don't think  it's upstreamable as is. If building against suil in a distro (in my case Fedora 32), there `libsuil_x11_in_gtk3.so` so `SUIL_MODULE_PREFIX` should be `lib`

**Comment by eszlari** [comment]
You could upstream a patch that guards the variables:

```
if(NOT SUIL_MODULE_PREFIX)
  set( SUIL_MODULE_PREFIX "lib" )
endif()
```
This way, they can be set on the command line:

```
cmake -DSUIL_MODULE_PREFIX=""
```

**Comment by hfiguiere** [comment]
This is the patch I'll submit upstream

**Comment by hfiguiere** [comment]
This is rebased on the current release.

**Comment by hfiguiere** [comment]
This last patch add the new "unified" extension support. In principle, this doesn't change anything yet for you. I tested it.

See https://github.com/flathub/org.freedesktop.LinuxAudio.BaseExtension/issues/1

**Comment by hfiguiere** [comment]
Anything else I need to do to get this merged?

**Comment by eszlari** [comment]
It's just that upstream hasn't even commented on your PR yet, and for me, it's very annoying to adjust patches to new releases.

**Comment by hfiguiere** [comment]
I could help with that when time comes. It's a small patch.

But if I had to wait for upstream for everything I'd never get anything done.

**Comment by eszlari** [comment]
That's why I prefer sed to patch: easier to change from the Github UI and often you don't even need to adjust it for a new release.

**Comment by hfiguiere** [comment]
Rebased on top of #55 . When #54 land (it was first), I'll rebase this.

Still don't know what's missing beside ustream reviewing and merging the patch.

**Pull request merged**
