### PR TITLE
Update to 2.2.2

### LINKED ISSUE #7: a new update 2.2.2
Hi, there is a new update 2.2.2

### PR DESCRIPTION
**Pull request by nedrichards**
Fixes #7

### CODE REVIEW

**Comment by nedrichards** [comment]
bot, build

**Comment by nedrichards** [comment]
Looks like the appdata needs some work:

> Error loading AppData file: org.audacityteam.Audacity has no recognised type

**Comment by jurf** [comment]
bot, build

(Sorry, 26 Feb is way too far back to find on Buildbot.)

**Comment by jurf** [comment]
That’s weird, the AppData passes `validate-relax` just fine.

**Comment by jurf** [comment]
OK, looks like it builds fine, but on my machine a `flatpak-builder --run` just shows:
```
❯ flatpak-builder --run appdir org.audacityteam.Audacity.json audacity

** (audacity:2): WARNING **: Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-L2F2aBdEd4: Connection refused
Gtk-Message: Failed to load module "pk-gtk-module"
Gtk-Message: Failed to load module "canberra-gtk-module"
Gtk-Message: Failed to load module "pk-gtk-module"
Gtk-Message: Failed to load module "canberra-gtk-module"
```
And exits. Nothing more.

**Comment by jurf** [comment]
Could anyone try this?

**Comment by Lvaskz** [comment]
Any Progress?

**Comment by Lvaskz** [comment]
So, I think audacity.flatpak can not to update to 2.22 version. Right?

**Comment by TingPing** [comment]
It was updated by another PR.

**Comment by Lvaskz** [comment]
Excuse my ignorance, but what does that mean?

**Comment by Lvaskz** [comment]
What is a RP?

**Comment by TingPing** [comment]
Pull Request but that isn't important. Just run `flatpak update` and you should get the new version.

**Comment by Lvaskz** [comment]
Thanks!

**Pull request closed without merging**
