### PR TITLE
Use freedesktop-sdk 19.08

### LINKED ISSUE #39: Update runtime to 19.08

### PR DESCRIPTION
**Pull request by jjardon**
Fixes #39

### CODE REVIEW

**Comment by jjardon** [comment]
bot buil

**Comment by eszlari** [comment]
Thanks, I fixed this (and other things).

**Comment by jjardon** [comment]
Thanks @eszlari 

Any reason to not use ffmpeg from the runtime though?

**Comment by eszlari** [comment]
I tried your patch and it didn't seem to work. Did you forget
```
mkdir -p /app/lib/ffmpeg
```
?
(taken from https://gitlab.com/freedesktop-sdk/freedesktop-sdk/blob/19.08/tests/test.codecs.ffmpeg-full.json)

But looking at https://gitlab.com/freedesktop-sdk/freedesktop-sdk/blob/19.08/elements/extensions/ffmpeg-full/ffmpeg.bst , this wouldn't be enough anyway, because some demuxers are missing (asf/wmv, flv).

**Comment by Erick555** [comment]
> I tried your patch and it didn't seem to work. Did you forget
> 
> mkdir -p /app/lib/ffmpeg
> 

Right, [totem has the same](https://github.com/flathub/org.gnome.Totem/blob/master/org.gnome.Totem.json#L314).

> But looking at https://gitlab.com/freedesktop-sdk/freedesktop-sdk/blob/19.08/elements/extensions/ffmpeg-full/ffmpeg.bst , this wouldn't be enough anyway, because some demuxers are missing (asf/wmv, flv).

Please open issue in https://gitlab.com/freedesktop-sdk/freedesktop-sdk/issues .

**Pull request closed without merging**
