### PR TITLE
use app id for icons, desktop and appdata file

### LINKED ISSUE #143: It seems like the .desktop file causes problems with window managers identifying the window
It seems like the flatpak's current .desktop file causes problems with window managers identifying the window:

[Steps to reproduce for the Phosh window manager are in a comment below.](https://github.com/flathub/org.audacityteam.Audacity/issues/143#issuecomment-1872322486)

In many window managers like Phosh or gnome-shell and I believe also KDE, that show an app icon to identify the running app, clicking that icon is supposed to auto-identify any of the already opened app windows to focus on them. But when the desktop file doesn't allow the WM/compositor to find the associated windows, it'll rather launch the app again (which will be prevented often by multi instance preventing code, and as a result turn the icon strangely entirely useless for a baffled user).

This "useless icon" phenomenon is what Audacity is currently showing at least with the Phosh wayland desktop I'm using.

Apparently, for this to work under wayland [the desktop file needs to be named after the app id](https://gitlab.alpinelinux.org/alpine/aports/-/issues/15619#note_365992) that was [specified in the desktop file](https://github.com/flathub/org.audacityteam.Audacity/blob/c924c40308b75ee3c6ee08ece3d357d43380ddee/org.audacityteam.Audacity.yaml#L1), and it seems like that would mean a file name of `org.audacityteam.Audacity.desktop` and [not `audacity.desktop`](https://github.com/flathub/org.audacityteam.Audacity/blob/c924c40308b75ee3c6ee08ece3d357d43380ddee/org.audacityteam.Audacity.yaml#L8).

### PR DESCRIPTION
**Pull request by Sertonix**
fixes #143

### CODE REVIEW

**Comment by hfiguiere** [comment]
What make you think this is a good change?

**Comment by Sertonix** [comment]
Using the app id is the standard:
> [Desktop files should be named with the application’s ID, followed by the `.desktop` file extension](https://docs.flatpak.org/en/latest/conventions.html#desktop-files)

And at least 1 DE (phosh) has problems when it is not done like that.

**Comment by hfiguiere** [comment]
This PR just break things.

I don't know what you are actually trying to do but this won't work.

**Comment by Sertonix** [comment]
Hm, ok sorry I expected that to be easier.

**Pull request closed without merging**
